defaults:
  - /data_new/sources
  - /data_new/population@population: global_set

_target_: src.data_new.datamodule.Corpus

name: global_set

sources:
  - ${data_new.sources.health}
  - ${data_new.sources.labour}